name: Security API Audit

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  api-audit:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: redis
      REDIS_HOST: 127.0.0.1

    services:
      redis:
        image: redis:7.0.15
        ports:
          - 6379:6379
      postgres:
        image: postgres:17.7
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Start Application
        run: php artisan serve &

      - name: Check If Server Is Running
        run: curl --retry 5 --retry-delay 2 http://localhost:8000

      - name: Export Documentation
        run: php artisan scramble:export

      - name: Start OWASP ZA
        uses: zaproxy/action-api-scan@v0.10
        with:
          target: http://localhost:8000
          format: openapi
          definition: api.json
          fail_action: false # ze względu na charakter testowy projektu

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v7
        with:
          name: zap-report
          path: zap-report.html
